name: Deploy Weekly Quest App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard
          
      - name: Lint HTML
        run: htmlhint "*.html"
        
      - name: Lint CSS
        run: stylelint "css/*.css"
  
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g lighthouse
          
      - name: Start local server
        run: |
          npm install -g http-server
          http-server . -p 8080 &
          sleep 5
          
      - name: Run Lighthouse CI
        run: |
          lighthouse http://localhost:8080 --output html --output-path ./lighthouse-report.html --chrome-flags="--headless --no-sandbox --disable-gpu"
          
      - name: Upload Lighthouse report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html
          
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g workbox-cli
          
      - name: Generate service worker
        run: workbox generateSW workbox-config.js
        
      - name: Create assets directories
        run: |
          mkdir -p assets/icons
          mkdir -p assets/screenshots
          
      - name: Create placeholder images
        run: |
          echo "Placeholder for icon" > assets/icons/icon-192x192.png
          echo "Placeholder for icon" > assets/icons/icon-512x512.png
          echo "Placeholder for screenshot" > assets/screenshots/home.png
          echo "Placeholder for screenshot" > assets/screenshots/recipes.png
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: weekly-quest-build
          path: |
            index.html
            offline.html
            manifest.json
            css/
            js/
            service-worker.js
            assets/
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: weekly-quest-build
          path: ./dist
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
